### ISSUE TITLE
TinyMCE toolbar size

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/40-backend-template#75]
### Steps to reproduce the issue

This:
https://github.com/joomla/40-backend-template/blob/master/administrator/templates/atum/_src/scss/vendor/_tinymce.scss#L3-L5

should 

``` css
.editor .toggle-editor {
margin-top: 1em;
}

```

on the class of the buttons bellow the editor
